CREATE TABLE tasks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	freq_value INT NOT NULL DEFAULT 7,
	freq_unit ENUM('days','hours') NOT NULL DEFAULT 'days',
	room VARCHAR(120) DEFAULT '',
	last_done DATETIME NULL,
	finished TINYINT(1) NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE courses (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	quantity VARCHAR(60) DEFAULT '',
	category VARCHAR(120) DEFAULT '',
	note VARCHAR(255) DEFAULT '',
	bought TINYINT(1) NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE meals (
	id INT AUTO_INCREMENT PRIMARY KEY,
	day ENUM('lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche') NOT NULL,
	moment ENUM('midi','soir') NOT NULL,
	meal TEXT NOT NULL,
	week_offset INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
